## Template-Programming in R

```{r eval=FALSE, echo=FALSE}
knitr::knit("Readme.Rmd", "Readme.md")
```

### Some ideas on working with templates in R

#### Functions:

```{r}
library("templates")
tFun <- templateFun(function() {
  s <- "great idea!!!"
  cat({{ toupper(begin) }}, s)
  invisible(NULL)
})

templateSub(tFun, begin ~ 'This is a')
templateEval(tFun, begin ~ 'This is a')
```


#### Expressions:

```{r}
tExpr <- templateExpr(local({
  s <- "great idea!!!"
  cat({{ toupper(begin) }}, s)
}))

templateSub(tExpr, begin ~ 'This is a')
templateEval(tExpr, begin ~ 'This is a')
templateEvalHere(tExpr)
```


#### Character:

```{r}
tChar <- templateChar('local({
  s <- "great idea!!!\n"
  cat({{ toupper(begin) }}, s)
})')

templateSub(tExpr, begin ~ 'This is a')
templateEval(tExpr, begin ~ 'This is a')
templateEvalHere(templateEval(tExpr, begin ~ 'This is a'))
```


### Some more usefull examples

#### MySQL Queries:

```{r}
templateRead <- function(fileName) {
  templateChar(paste(readLines(fileName), collapse = "\n"))
}

collapseInParan <- function(x) paste("(", paste(x, collapse = ", "), ")")

sqlTemplate <- templateRead(system.file("tmp.sql", package = "templates"))

sqlTemplate

templateSub(
  sqlTemplate,
  ids = collapseInParan(1:10)
)

sqlTemplate <- templateExpr(
  `SELECT *
    FROM someTable
  WHERE something IN {{ collapseInParan(ids) }};`
)

templateEval(
  sqlTemplate, 
  ids ~ 1:10
)
```

